id: IC2C929AA
ocr_import_info:
  bdrc_scan_id: W1KG25320
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-09-12 14:07:15.309996
last_modified: 2023-02-01 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG25320
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG25320
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྟ་ནག་རྣམ་འགྲེལ།
  languages:
  - bo
  author: རྟ་ནག་པ་དགེ་འདུན་བློ་བཟང་།
bases:
  I1KG25322:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25322
      total_pages: 446
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1KG25322.txt
    order: 1
  I1KG25323:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25323
      total_pages: 704
      volume_number: 2
      volume_pages_bdrc_intro: 2
    base_file: I1KG25323.txt
    order: 2
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
